<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="GM.API.Application" Version="1.7.0" />
        <PackageReference Include="GM.Mediator" Version="2.0.0" />
        <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.11" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="GM.OTP" Version="1.2.0" />
      <ProjectReference Include="..\GM.OTP.Sample.Common\GM.OTP.Sample.Common.csproj" />
      <ProjectReference Include="..\GM.OTP.Sample.Domain\GM.OTP.Sample.Domain.csproj" />
    </ItemGroup>

</Project>
